alias adb=/home/jmw/Android/Sdk/platform-tools/adb
adb shell pm disable-user --user 0 com.android.hplayer
adb shell pm disable-user --user 0 com.android.browser
adb shell pm disable-user --user 0 com.android.calendar
adb shell pm disable-user --user 0 com.android.firewall
adb shell pm disable-user --user 0 com.android.hplayer
adb shell pm disable-user --user 0 com.android.providers.downloads.ui
adb shell pm disable-user --user 0 com.android.sos
adb shell pm disable-user --user 0 com.hmct.account
adb shell pm disable-user --user 0 com.hmct.antivirus
adb shell pm disable-user --user 0 com.hmct.assist
adb shell pm disable-user --user 0 com.hmct.einklauncher.plugin.wechat
adb shell pm disable-user --user 0 com.hmct.imageedit
adb shell pm disable-user --user 0 com.hmct.mobileclear
adb shell pm disable-user --user 0 com.hmct.questionnaire
adb shell pm disable-user --user 0 com.hmct.theme
adb shell pm disable-user --user 0 com.hmct.voiceassist
adb shell pm disable-user --user 0 com.hmct.voicetranslate
adb shell pm disable-user --user 0 com.hmct.music
adb shell pm disable-user --user 0 com.hmct.hmctmanual
adb shell pm disable-user --user 0 com.hmct.userexperienceprogram
adb shell pm disable-user --user 0 com.tencent.soter.soterserver
adb shell pm disable-user --user 0 org.hapjs.mockup
adb shell pm disable-user --user 0 com.hmct.jdreader
adb shell pm disable-user --user 0 com.tencent.android.location
adb shell pm disable-user --user 0 com.hmct.hiphone.juplugin
adb shell pm disable-user --user 0 com.hmct.einklauncher.plugin.wechat
adb shell pm disable-user --user 0 com.hmct.voiceassist
adb shell pm disable-user --user 0 com.hmct.ftmode
adb shell pm disable-user --user 0 com.hmct.semantic.analysis
